# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install flake8
      run : pip install flake8
     
    - name: Lint with flake8
      run: |
        flake8 preproc.py test_ml.py train_model.py ml/model.py main.py local_api.py

    - name: Test with pytest
      run: |
        pytest

